import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import TopEffect from "@/components/top-effect";
import Navbar from "@/components/navbar";

const manrope = Manrope({ subsets: ["latin"], weight: ['200', '300', '400', '500', '600', '700', '800'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <div className="bg-greyish text-black min-h-screen w-full max-w-full">
          <Navbar />
          {children}   
        </div>
      </body>
    </html>
  );
}
