import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import TopEffect from "@/components/top-effect";
import Navbar from "@/components/navbar";

const manrope = Manrope({ subsets: ["latin"], weight: ['200', '300', '400', '500', '600', '700', '800'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.className}`}>
        <div className="relative text-black bg-white min-h-screen w-full max-w-full">
          {/* <svg
            className='absolute top-0 left-0 -z-10 min-h-screen w-full stroke-gray-300'
            aria-hidden='true'>
            <defs>
              <pattern
                id='0787a7c5-978c-4f66-83c7-11c213f99cb7'
                width={200}
                height={200}
                x='50%'
                y={0}  
                patternUnits='userSpaceOnUse'>
                <path d='M.5 200V.5H200' fill='none' />
              </pattern>
            </defs>
            <rect
              width='100%'
              height='100%'
              strokeWidth={0}
              fill='url(#0787a7c5-978c-4f66-83c7-11c213f99cb7)'
            />
          </svg> */}
          <Navbar />
          {children}   
        </div>
      </body>
    </html>
  );
}
